version: '3.7'
networks:
  auth-net:
    driver: bridge
services:
  integTest:
    image: ghcr.io/datakaveri/aaa-depl:latest
    environment:
      - AUTH_URL=https://authorization.iudx.org.in
      - LOG_LEVEL=INFO
      - AUTH_JAVA_OPTS=-Xmx1024m
    volumes:
      - /home/ubuntu/configs/aaa-config-integ.json:/usr/share/app/configs/config.json
      - /home/ubuntu/configs/aaa-keystore.jks:/usr/share/app/configs/keystore.jks
    depends_on:
      - "zookeeper"
    command: bash -c "exec java $$AUTH_JAVA_OPTS  -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -jar ./fatjar.jar  --host $$(hostname) -c configs/config.json"
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - auth-net

  zookeeper:
    image: zookeeper:latest
    expose: 
      - "2181"
    networks:
      - auth-net
